/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.pedidos;
import controlador.Controlador;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.NoResultException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Pedido;
import modelo.Pedido_;
/**
 *
 * @author Acer
 */
public class ABMPedidos extends javax.swing.JFrame {

    /**
     * Creates new form ABMPedidos
     */
    private final Controlador contro;
    private final JFrame previo;
    public ABMPedidos(Controlador c, JFrame p) {
        this.contro = c;
        this.previo = p;
        initComponents();
        /*Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2, height/2);*/
        this.cmbxCriterio.setSelectedIndex(-1);
        setLocationRelativeTo(null);
        setVisible(true);
        this.previo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVistaPedidos = new javax.swing.JList();
        cmbxCriterio = new javax.swing.JComboBox<>();
        txtCriterio = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar la felicidad!!! o pedidos.");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstVistaPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVistaPedidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVistaPedidosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVistaPedidos);

        cmbxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "CUIT", "Fecha" }));

        btnBorrar.setText("Eliminar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Ver");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cmbxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnMostrar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        //
        try{
            
            if (!"".equals(this.txtCriterio.getText())) {
                switch (this.cmbxCriterio.getSelectedIndex()) {
                    //ID Pedido
                    case 0:
                        //do something
                        this.lstVistaPedidos.setListData(this.contro.buscarPedidos(Pedido_.idPedido, Long.parseLong(this.txtCriterio.getText())).toArray());
                        break;
                    //CUIT propietario
                    case 1:
                        Cliente propietario;
                        propietario = this.contro.buscarClienteCUIT(this.txtCriterio.getText());
                        this.lstVistaPedidos.setListData(this.contro.buscarPedidos(Pedido_.propietario, propietario).toArray());
                        break;
                    //FECHA PRIMER ENTREGA
                    case 2:
                        
                        Date d = this.contro.dateParser(this.txtCriterio.getText());
                        this.lstVistaPedidos.setListData(this.contro.buscarPedidos(Pedido_.entregaInicial, d).toArray());
                        break;
                }
            } else {
                this.lstVistaPedidos.setListData(this.contro.mostrarPedidos().toArray());
            }
        }catch (ParseException | NumberFormatException e){
            System.out.println("Hubo un error, pero no te preocupes. :D");
        }catch (NoResultException error){
            System.out.println("No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        
        if (!this.lstVistaPedidos.isSelectionEmpty()){
            try {
                Pedido p = (Pedido) this.lstVistaPedidos.getSelectedValue();
                this.contro.eliminarPedido(p);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void lstVistaPedidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVistaPedidosValueChanged
        // Cuando se hace click en un resultado, se abre una ventana para poder ver
        // las entregas que dorresponden a ese pedido.
        
    }//GEN-LAST:event_lstVistaPedidosValueChanged

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if (!this.lstVistaPedidos.isSelectionEmpty()){
            Pedido unPedido = (Pedido) this.lstVistaPedidos.getSelectedValue();
            VentanaNuevoPedido vnp;
            vnp = new VentanaNuevoPedido(this.contro, this, unPedido);
            vnp.setVisible(true);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cmbxCriterio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstVistaPedidos;
    private javax.swing.JTextField txtCriterio;
    // End of variables declaration//GEN-END:variables
}
