/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.entregas;
import controlador.Controlador;
import java.text.DateFormat;
import javax.swing.JFrame;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.TableModel;
import modelo.Articulo;
import modelo.Entrega;
import modelo.Envase;
import modelo.Pedido;
/**
 *
 * @author Acer
 */
public class VentanaEntrega extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEntrega
     */
    private final Controlador controlador;
    private final JFrame previo;
    private final Date fechaEntrega;
    private final Pedido pedido;
    private final Entrega entrega;
    private DefaultListModel lsm;
    //Constructor de la Clase.
    public VentanaEntrega(Controlador c, JFrame p, Date fEnt, Pedido pedido) {
        this.controlador = c;
        this.previo = p;
        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String s = df.format(fEnt);
        this.fechaEntrega = fEnt;
        this.pedido = pedido;
        initComponents();
        this.entrega = this.controlador.buscarEntrega(fechaEntrega, pedido.getIdPedido());
        limpiar();
        lsm = new DefaultListModel();
        
        //Establecer el id de la entrega en la etiqueta.
        this.lblIDentrega.setText(this.entrega.getIdEntrega().toString());
        this.lblFechaEntrega.setText(s);
        this.lblNroPedido.setText(this.pedido.getIdPedido().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarArt = new javax.swing.JButton();
        lblNroPedido = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        cmbxArticulo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbxEnvase = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lblIDentrega = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDetalle = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONFIGURAR ENTREGA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Artículo");

        jLabel2.setText("Cantidad");

        txtCantidad.setName("txtNrCliente"); // NOI18N

        jLabel3.setText("Nro pedido");

        jLabel4.setText("Fecha");

        btnAgregarArt.setText("Agregar articulo");
        btnAgregarArt.setName("BotonBuscar"); // NOI18N
        btnAgregarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArtActionPerformed(evt);
            }
        });

        lblNroPedido.setText("-Nro Pedido-");

        lblFechaEntrega.setText("- Fecha -");

        cmbxArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxArticuloActionPerformed(evt);
            }
        });

        jLabel5.setText("Envase");

        jLabel6.setText("ID Entrga");

        lblIDentrega.setText("- Id Entrega -");

        lstDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstDetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(lblFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIDentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarArt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbxEnvase, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbxArticulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNroPedido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFechaEntrega))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblIDentrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbxArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbxEnvase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarArt)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArtActionPerformed
        // TODO add your handling code here:
        try{
            
            this.controlador.agregarLineaEntrega(
                    this.fechaEntrega,
                    this.entrega,
                    Integer.parseInt(this.txtCantidad.getText()),
                //this.cmbxTipoArticulo.getSelectedItem(),
                    (Articulo) this.cmbxArticulo.getSelectedItem(),
                    (Envase) this.cmbxEnvase.getSelectedItem());
            this.txtCantidad.setText("");
            limpiar();
        } catch (NumberFormatException e) {
            this.txtCantidad.setText("");
            this.txtCantidad.grabFocus();
        }
        
        
    }//GEN-LAST:event_btnAgregarArtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.previo.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void cmbxArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxArticuloActionPerformed
        // TODO add your handling code here:
        Articulo art;
        art = (Articulo) this.cmbxArticulo.getSelectedItem();
        DefaultComboBoxModel modeloCombo;
        modeloCombo = new DefaultComboBoxModel(this.controlador.buscarEnvaseTipo(art.getTipo()).toArray());
        this.cmbxEnvase.setModel(modeloCombo);
    }//GEN-LAST:event_cmbxArticuloActionPerformed

    private void limpiar(){
        /*this.lblFechaEntrega.setText("");
        this.lblIDentrega.setText("");
        this.lblNroPedido.setText("");*/
        DefaultComboBoxModel modeloCombo;
        modeloCombo = new DefaultComboBoxModel(this.controlador.listarArticulos().toArray());
        this.cmbxArticulo.setModel(modeloCombo);
        this.cmbxArticulo.setSelectedIndex(0);
        Entrega unaEntrega = this.controlador.buscarEntrega(this.entrega.getIdEntrega());
        this.lstDetalle.setListData(unaEntrega.getDetalle().toArray());
        //this.cmbxEnvase.setSelectedIndex(0);
        
        
    }

    // <editor-fold defaultstate="collapsed" desc="Elementos de la ventana">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArt;
    private javax.swing.JComboBox cmbxArticulo;
    private javax.swing.JComboBox cmbxEnvase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblIDentrega;
    private javax.swing.JLabel lblNroPedido;
    private javax.swing.JList lstDetalle;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
