/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.articulos;
import controlador.Controlador;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.*;
import modelo.Articulo;
import modelo.Articulo_;
import modelo.TipoArticulo;
/**
 *
 * @author Diego Raul Fernandez
 */
public class VentanaArticulo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaArticulo
     */
    private final JFrame vp;
    private final Controlador controlador;
    public VentanaArticulo(Controlador c, JFrame previo) {
        this.controlador = c;
        this.vp = previo;
        initComponents();
        this.vp.setVisible(false);
        limpiar();
        /*Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2, height/2);*/
        setLocationRelativeTo(null);
        setVisible(true);
        //poblar el comboBox de tipo articulo.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiametro = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtLargo = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbxTipoArticulo = new javax.swing.JComboBox<>();
        btnGuardarArticulo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstArticulos = new javax.swing.JList();
        cmbxCriterioBusqueda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblIdArticulo = new javax.swing.JLabel();
        btnEliminArt = new javax.swing.JButton();
        cmbxTipArt = new javax.swing.JComboBox();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana articulos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("-- ID --");
        lblID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nombre");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Largo");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Diametro");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Ancho");

        txtDiametro.setText("jTextField1");

        txtDescripcion.setText("jTextField1");

        txtLargo.setText("jTextField1");

        txtAncho.setText("jTextField1");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Tipo de articulo");

        cmbxTipoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTipoArticuloActionPerformed(evt);
            }
        });

        btnGuardarArticulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego Raul Fernandez\\Pictures\\UN_MAS.png")); // NOI18N
        btnGuardarArticulo.setText("Guardar");
        btnGuardarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArticuloActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Buscar por:");

        lstArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstArticulos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArticulosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstArticulos);

        cmbxCriterioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Largo", "Ancho", "Diámetro", "Tipo de Artículo" }));
        cmbxCriterioBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxCriterioBusquedaActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Criterio");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblIdArticulo.setText("ID Artículo");

        btnEliminArt.setText("Eliminar");
        btnEliminArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminArtActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbxTipArt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(cmbxCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminArt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblID)
                        .addComponent(lblIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbxCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbxTipArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbxTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarArticulo)
                            .addComponent(btnEliminArt)
                            .addComponent(btnLimpiar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            List resultado;
            switch (this.cmbxCriterioBusqueda.getSelectedIndex()) {
                //ID, 
                case 0:
                    resultado = this.controlador.buscarArticulos(Articulo_.idArticulo,
                            Long.parseLong(this.txtBuscar.getText()));
                    if (resultado.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        this.lstArticulos.setListData(resultado.toArray());
                    }
                    break;
                //Nombre, 
                case 1:
                    resultado = this.controlador.buscarArticulos(Articulo_.descripcion,
                            this.txtBuscar.getText());
                    if (resultado.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        this.lstArticulos.setListData(resultado.toArray());
                    }
                    break;
                //Largo,
                case 2:
                    resultado = this.controlador.buscarArticulos(Articulo_.largo,
                            Double.parseDouble(this.txtBuscar.getText()));
                    if (resultado.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        this.lstArticulos.setListData(resultado.toArray());
                    }
                    break;
                //Ancho,
                case 3:
                    resultado = this.controlador.buscarArticulos(Articulo_.ancho,
                            Double.parseDouble(this.txtBuscar.getText()));
                    if (resultado.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        this.lstArticulos.setListData(resultado.toArray());
                    }
                    break;
                //"Diámetro",
                case 4:
                    resultado = this.controlador.buscarArticulos(Articulo_.diametro,
                            Double.parseDouble(this.txtBuscar.getText()));
                    if (resultado.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        this.lstArticulos.setListData(resultado.toArray());
                    }
                    break;
                //"Tipo de Artículo"
                case 5:
                    resultado = this.controlador.buscarArticulos(Articulo_.tipo,
                            (TipoArticulo)this.cmbxTipArt.getSelectedItem());
                    if (resultado.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        this.lstArticulos.setListData(resultado.toArray());
                    }
                    break;
                default:                
            }
        } catch (NumberFormatException numberFormatException) {
        } catch (HeadlessException headlessException) {
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArticuloActionPerformed
        // TODO add your handling code here:
        try {
            TipoArticulo ta;
            ta = (TipoArticulo) this.cmbxTipoArticulo.getSelectedItem();
            if (this.lstArticulos.isSelectionEmpty()){
                if (!"".equals(this.txtDescripcion.getText())) {
                    this.controlador.nuevoArticulo(this.txtDescripcion.getText().toUpperCase(),
                            Double.parseDouble(this.txtLargo.getText()),
                            Double.parseDouble(this.txtAncho.getText()),
                            Double.parseDouble(this.txtDiametro.getText()),
                            //env,
                            ta);
                    limpiar();
                } else {
                    System.out.println("Te olvidaste poner una descripción al ertículo. :@");
                    this.txtDescripcion.grabFocus();
                }
                
            } else {
                Articulo art = (Articulo) this.lstArticulos.getSelectedValue();
                this.controlador.editarArticulo(art, this.txtDescripcion.getText().toUpperCase(),
                        Double.parseDouble(this.txtLargo.getText()),
                        Double.parseDouble(this.txtAncho.getText()),
                        Double.parseDouble(this.txtDiametro.getText()));
                limpiar();
            }
        } catch (NumberFormatException | HeadlessException numberFormatException) {
            JOptionPane.showMessageDialog(null, "No es un Número", "Error", JOptionPane.ERROR_MESSAGE);
            this.txtLargo.grabFocus();
        }catch (Exception usop){
            JOptionPane.showMessageDialog(null, usop.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarArticuloActionPerformed

    private void cmbxTipoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTipoArticuloActionPerformed
        // TODO add your handling code here:
        //TipoArticulo ta;
        //ta = (TipoArticulo) this.cmbxTipoArticulo.getSelectedItem();
        /*DefaultComboBoxModel modeloCombo;
        modeloCombo = new DefaultComboBoxModel(this.controlador.buscarEnvaseTipo(ta).toArray());
        this.cmbxEnvase.setModel(modeloCombo);
        this.cmbxEnvase.setSelectedIndex(0);*/
        //this.lstEnvases.setListData(this.controlador.buscarEnvaseTipo(ta).toArray());
        
    }//GEN-LAST:event_cmbxTipoArticuloActionPerformed

    private void btnEliminArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminArtActionPerformed
        // TODO add your handling code here:
        try {
            Articulo articulo = (Articulo) this.lstArticulos.getSelectedValue();
            if (articulo != null) {
                this.controlador.eliminarArticulo(articulo);
            }
        } catch (Exception e) {
            System.out.println("No cha, no se puede eliminar viteh!!!");
        }
        
        limpiar();
    }//GEN-LAST:event_btnEliminArtActionPerformed

    private void lstArticulosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArticulosValueChanged
        // TODO add your handling code here:
        if (!this.lstArticulos.isSelectionEmpty()) {
            Articulo a = (Articulo) this.lstArticulos.getSelectedValue();
            this.lblID.setText(a.getIdArticulo().toString());
            this.txtDescripcion.setText(a.getDescripcion());
            this.txtLargo.setText(a.getLargo().toString());
            this.txtAncho.setText(a.getAncho().toString());
            this.txtDiametro.setText(a.getDiametro().toString());
            this.cmbxTipoArticulo.setSelectedItem(a.getTipo());
        }
    }//GEN-LAST:event_lstArticulosValueChanged

    private void cmbxCriterioBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxCriterioBusquedaActionPerformed
        // TODO add your handling code here:
        if (this.cmbxCriterioBusqueda.getSelectedIndex() == 5){
            this.cmbxTipArt.setVisible(true);
            this.txtBuscar.setVisible(false);
            //mosatrar los tipos de articulos en un combobox nuevo.
            DefaultComboBoxModel modeloCombo;
            modeloCombo = new DefaultComboBoxModel(this.controlador.listarTipoArticulo().toArray());
            this.cmbxTipArt.setModel(modeloCombo);
        }else{
            this.txtBuscar.setVisible(true);
            this.cmbxTipArt.setVisible(false);
        }
    }//GEN-LAST:event_cmbxCriterioBusquedaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    private void limpiar(){
        this.txtBuscar.setVisible(true);
        this.cmbxTipArt.setVisible(false);
        this.lblID.setText("");
        this.txtDiametro.setText("");
        this.txtAncho.setText("");
        this.txtBuscar.setText("");
        this.txtDescripcion.setText("");
        this.txtLargo.setText("");
        DefaultComboBoxModel modeloCombo;
        modeloCombo = new DefaultComboBoxModel(this.controlador.listarTipoArticulo().toArray());
        this.cmbxTipoArticulo.setModel(modeloCombo);
        this.cmbxTipoArticulo.setSelectedIndex(-1);
        //DefaultListModel modeloLista = new DefaultListModel();
        this.lstArticulos.setListData(this.controlador.listarArticulos().toArray());
        this.lstArticulos.clearSelection();
    }
    //<editor-fold defaultstate="collapsed" desc="Elementos de la ventana">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminArt;
    private javax.swing.JButton btnGuardarArticulo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbxCriterioBusqueda;
    private javax.swing.JComboBox cmbxTipArt;
    private javax.swing.JComboBox<String> cmbxTipoArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdArticulo;
    private javax.swing.JList lstArticulos;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDiametro;
    private javax.swing.JTextField txtLargo;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
